-- -- Netrw 비활성화 (기본 트리와 충돌 방지)
-- vim.g.loaded_netrw = 1
-- vim.g.loaded_netrwPlugin = 1
-- return {
--   "nvim-neo-tree/neo-tree.nvim",
--   opts = {
--     filesystem = {
--       bind_to_cwd = false,
--       filtered_items = {
--         visible = true,
--         hide_dotfiles = false,
--         hide_gitignored = false,
--       },
--     },
--   },
--   init = function()
--     vim.api.nvim_create_autocmd("VimEnter", {
--       once = true,
--       callback = function()
--         vim.defer_fn(function()
--           require("neo-tree.command").execute({ action = "show" })
--         end, 100)
--       end,
--     })
--   end,
-- }
return {}