[opener]
edit = [
	{ run = 'nvim "$@"', block = true, desc = "Edit with Neovim" },
]

[open]
rules = [
	{ name = "*.txt", use = "edit" },
	{ name = "*.md",  use = "edit" },
	{ name = "*.lua", use = "edit" },
    { mime = "text/*", use = "edit" },
]